[project]
name = "jira-cli"
version = "0.1"
description = "Jira CLI"
readme = "README.md"
requires-python = ">=3.14.0"

[tool.setuptools.packages.find]
where = ["src"]
include = ["*"]
exclude = ["*test*"]
namespaces = true

[tool.pytest.ini_options]
addopts = '-n auto --ruff'
